// Constants for dimenstions.
export const ADD_DIMENSION = "ADD_DIMENSION";
export const FETCH_DIMENSIONS = "FETCH_DIMENSIONS";
export const FETCH_DIMENSIONS_FULFILLED = "FETCH_DIMENSIONS_FULFILLED";
export const FETCH_DIMENSIONS_REJECTED = "FETCH_DIMENSIONS_REJECTED";
export const REMOVE_DIMENSION = "REMOVE_DIMENSION";

// Constants for dimension values.
export const ADD_DIMENSION_VALUE = "ADD_DIMENSION_VALUE";
export const FETCH_DIMENSION_VALUES = "FETCH_DIMENSION_VALUES";
export const FETCH_DIMENSION_VALUES_FULFILLED =
  "FETCH_DIMENSION_VALUES_FULFILLED";
export const FETCH_DIMENSION_VALUES_REJECTED =
  "FETCH_DIMENSION_VALUES_REJECTED";
export const REMOVE_DIMENSION_VALUE = "REMOVE_DIMENSION_VALUE";

// Constants for save button.
export const SAVE_SERIES = "SAVE_SERIES";
export const SAVE_SERIES_FULFILLED = "SAVE_SERIES_FULFILLED";
export const SAVE_SERIES_REJECTED = "SAVE_SERIES_REJECTED";
